name: Build Container

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: "0 10 * * *" # everyday at 10am
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request_target:
    branches:
      - main

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ${{ github.repository }}/ruby-postgis
  # TODO: Set registry. Use docker.io for DockerHub
  REGISTRY: ghcr.io

jobs:
  docker:
    strategy:
      matrix:
        postgres: [10, 9.6]
        postgis: [2.4]
        include:
          - postgres: 11
            postgis: 3.0
          - postgres: 12
            postgis: 3.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Container metadata
        id: metadata
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.postgres }}-${{ matrix.postgis }}
      - uses: docker/setup-buildx-action@v1

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres }}
            POSTGIS_VERSION=${{ matrix.postgis }}
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.metadata.outputs.tags }}
          labels: |
            ${{ steps.metadata.outputs.labels }}
